///
/// @Generated by Mockolo
///



import AppKit
import Combine
import CoreWLAN
import Foundation
@testable import SaneBar
import IOKit
import KeyboardShortcuts
import SwiftUI
import os


final class PersistenceServiceProtocolMock: PersistenceServiceProtocol, @unchecked Sendable {
    init() { }


    private let saveSettingsState = MockoloMutex(MockoloHandlerState<SaneBarSettings, @Sendable (SaneBarSettings) throws -> ()>())
    var saveSettingsCallCount: Int {
        return saveSettingsState.withLock(\.callCount)
    }
    var saveSettingsArgValues: [SaneBarSettings] {
        return saveSettingsState.withLock(\.argValues).map(\.value)
    }
    var saveSettingsHandler: (@Sendable (SaneBarSettings) throws -> ())? {
        get { saveSettingsState.withLock(\.handler) }
        set { saveSettingsState.withLock { $0.handler = newValue } }
    }
    func saveSettings(_ settings: SaneBarSettings) throws {
        warnIfNotSendable(settings)
        let saveSettingsHandler = saveSettingsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((settings)))
            return state.handler
        }
        if let saveSettingsHandler = saveSettingsHandler {
            try saveSettingsHandler(settings)
        }
        
    }

    private let loadSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () throws -> SaneBarSettings>())
    var loadSettingsCallCount: Int {
        return loadSettingsState.withLock(\.callCount)
    }
    var loadSettingsHandler: (@Sendable () throws -> SaneBarSettings)? {
        get { loadSettingsState.withLock(\.handler) }
        set { loadSettingsState.withLock { $0.handler = newValue } }
    }
    func loadSettings() throws -> SaneBarSettings {
        let loadSettingsHandler = loadSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let loadSettingsHandler = loadSettingsHandler {
            return try loadSettingsHandler()
        }
        fatalError("loadSettingsHandler returns can't have a default value thus its handler must be set")
    }

    private let clearAllState = MockoloMutex(MockoloHandlerState<Never, @Sendable () throws -> ()>())
    var clearAllCallCount: Int {
        return clearAllState.withLock(\.callCount)
    }
    var clearAllHandler: (@Sendable () throws -> ())? {
        get { clearAllState.withLock(\.handler) }
        set { clearAllState.withLock { $0.handler = newValue } }
    }
    func clearAll() throws {
        let clearAllHandler = clearAllState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let clearAllHandler = clearAllHandler {
            try clearAllHandler()
        }
        
    }
}

final class SearchServiceProtocolMock: SearchServiceProtocol, @unchecked Sendable {
    init() { }


    private let getRunningAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getRunningAppsCallCount: Int {
        return getRunningAppsState.withLock(\.callCount)
    }
    var getRunningAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getRunningAppsState.withLock(\.handler) }
        set { getRunningAppsState.withLock { $0.handler = newValue } }
    }
    func getRunningApps() async -> [RunningApp] {
        let getRunningAppsHandler = getRunningAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getRunningAppsHandler = getRunningAppsHandler {
            return await getRunningAppsHandler()
        }
        return [RunningApp]()
    }

    private let activateState = MockoloMutex(MockoloHandlerState<RunningApp, @Sendable (RunningApp) async -> ()>())
    var activateCallCount: Int {
        return activateState.withLock(\.callCount)
    }
    var activateArgValues: [RunningApp] {
        return activateState.withLock(\.argValues).map(\.value)
    }
    var activateHandler: (@Sendable (RunningApp) async -> ())? {
        get { activateState.withLock(\.handler) }
        set { activateState.withLock { $0.handler = newValue } }
    }
    func activate(app: RunningApp) async {
        warnIfNotSendable(app)
        let activateHandler = activateState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((app)))
            return state.handler
        }
        if let activateHandler = activateHandler {
            await activateHandler(app)
        }
        
    }
}

class NetworkTriggerServiceProtocolMock: NetworkTriggerServiceProtocol {
    init() { }
    init(currentSSID: String? = nil) {
        self.currentSSID = currentSSID
    }



    var currentSSID: String? = nil

    private(set) var configureCallCount = 0
    var configureArgValues = [MenuBarManager]()
    var configureHandler: ((MenuBarManager) -> ())?
    func configure(menuBarManager: MenuBarManager) {
        configureCallCount += 1
        configureArgValues.append(menuBarManager)
        if let configureHandler = configureHandler {
            configureHandler(menuBarManager)
        }
        
    }

    private(set) var startMonitoringCallCount = 0
    var startMonitoringHandler: (() -> ())?
    func startMonitoring() {
        startMonitoringCallCount += 1
        if let startMonitoringHandler = startMonitoringHandler {
            startMonitoringHandler()
        }
        
    }

    private(set) var stopMonitoringCallCount = 0
    var stopMonitoringHandler: (() -> ())?
    func stopMonitoring() {
        stopMonitoringCallCount += 1
        if let stopMonitoringHandler = stopMonitoringHandler {
            stopMonitoringHandler()
        }
        
    }
}

class HoverServiceProtocolMock: HoverServiceProtocol {
    init() { }
    init(isHovering: Bool = false) {
        self.isHovering = isHovering
    }



    var isHovering: Bool = false

    private(set) var configureCallCount = 0
    var configureArgValues = [(mainItem: NSStatusItem, separatorItem: NSStatusItem)]()
    var configureHandler: ((NSStatusItem, NSStatusItem, @escaping () -> Void, @escaping () -> Void) -> ())?
    func configure(mainItem: NSStatusItem, separatorItem: NSStatusItem, onHoverStart: @escaping () -> Void, onHoverEnd: @escaping () -> Void) {
        configureCallCount += 1
        configureArgValues.append((mainItem, separatorItem))
        if let configureHandler = configureHandler {
            configureHandler(mainItem, separatorItem, onHoverStart, onHoverEnd)
        }
        
    }

    private(set) var setEnabledCallCount = 0
    var setEnabledArgValues = [Bool]()
    var setEnabledHandler: ((Bool) -> ())?
    func setEnabled(_ enabled: Bool) {
        setEnabledCallCount += 1
        setEnabledArgValues.append(enabled)
        if let setEnabledHandler = setEnabledHandler {
            setEnabledHandler(enabled)
        }
        
    }

    private(set) var setDelayCallCount = 0
    var setDelayArgValues = [TimeInterval]()
    var setDelayHandler: ((TimeInterval) -> ())?
    func setDelay(_ delay: TimeInterval) {
        setDelayCallCount += 1
        setDelayArgValues.append(delay)
        if let setDelayHandler = setDelayHandler {
            setDelayHandler(delay)
        }
        
    }
}

class TriggerServiceProtocolMock: TriggerServiceProtocol {
    init() { }


    private(set) var configureCallCount = 0
    var configureArgValues = [MenuBarManager]()
    var configureHandler: ((MenuBarManager) -> ())?
    func configure(menuBarManager: MenuBarManager) {
        configureCallCount += 1
        configureArgValues.append(menuBarManager)
        if let configureHandler = configureHandler {
            configureHandler(menuBarManager)
        }
        
    }

    private(set) var stopMonitoringCallCount = 0
    var stopMonitoringHandler: (() -> ())?
    func stopMonitoring() {
        stopMonitoringCallCount += 1
        if let stopMonitoringHandler = stopMonitoringHandler {
            stopMonitoringHandler()
        }
        
    }
}

class HidingServiceProtocolMock: HidingServiceProtocol {
    init() { }
    init(state: HidingState, isAnimating: Bool = false) {
        self._state = state
        self.isAnimating = isAnimating
    }



    private var _state: HidingState!
    var state: HidingState {
        get { return _state }
        set { _state = newValue }
    }


    var isAnimating: Bool = false

    private(set) var configureCallCount = 0
    var configureArgValues = [(delimiterItem: NSStatusItem, alwaysHiddenDelimiter: NSStatusItem?)]()
    var configureHandler: ((NSStatusItem, NSStatusItem?) -> ())?
    func configure(delimiterItem: NSStatusItem, alwaysHiddenDelimiter: NSStatusItem?) {
        configureCallCount += 1
        configureArgValues.append((delimiterItem, alwaysHiddenDelimiter))
        if let configureHandler = configureHandler {
            configureHandler(delimiterItem, alwaysHiddenDelimiter)
        }
        
    }

    private(set) var toggleCallCount = 0
    var toggleArgValues = [Bool]()
    var toggleHandler: ((Bool) async -> ())?
    func toggle(withModifier: Bool) async {
        toggleCallCount += 1
        toggleArgValues.append(withModifier)
        if let toggleHandler = toggleHandler {
            await toggleHandler(withModifier)
        }
        
    }

    private(set) var showCallCount = 0
    var showHandler: (() async -> ())?
    func show() async {
        showCallCount += 1
        if let showHandler = showHandler {
            await showHandler()
        }
        
    }

    private(set) var hideCallCount = 0
    var hideHandler: (() async -> ())?
    func hide() async {
        hideCallCount += 1
        if let hideHandler = hideHandler {
            await hideHandler()
        }
        
    }

    private(set) var showAlwaysHiddenCallCount = 0
    var showAlwaysHiddenHandler: (() async -> ())?
    func showAlwaysHidden() async {
        showAlwaysHiddenCallCount += 1
        if let showAlwaysHiddenHandler = showAlwaysHiddenHandler {
            await showAlwaysHiddenHandler()
        }
        
    }

    private(set) var hideAlwaysHiddenCallCount = 0
    var hideAlwaysHiddenHandler: (() async -> ())?
    func hideAlwaysHidden() async {
        hideAlwaysHiddenCallCount += 1
        if let hideAlwaysHiddenHandler = hideAlwaysHiddenHandler {
            await hideAlwaysHiddenHandler()
        }
        
    }
}

class KeyboardShortcutsServiceProtocolMock: KeyboardShortcutsServiceProtocol {
    init() { }


    private(set) var registerAllHandlersCallCount = 0
    var registerAllHandlersHandler: (() -> ())?
    func registerAllHandlers() {
        registerAllHandlersCallCount += 1
        if let registerAllHandlersHandler = registerAllHandlersHandler {
            registerAllHandlersHandler()
        }
        
    }

    private(set) var unregisterAllHandlersCallCount = 0
    var unregisterAllHandlersHandler: (() -> ())?
    func unregisterAllHandlers() {
        unregisterAllHandlersCallCount += 1
        if let unregisterAllHandlersHandler = unregisterAllHandlersHandler {
            unregisterAllHandlersHandler()
        }
        
    }
}

class MenuBarAppearanceServiceProtocolMock: MenuBarAppearanceServiceProtocol {
    init() { }


    private(set) var updateAppearanceCallCount = 0
    var updateAppearanceArgValues = [MenuBarAppearanceSettings]()
    var updateAppearanceHandler: ((MenuBarAppearanceSettings) -> ())?
    func updateAppearance(_ settings: MenuBarAppearanceSettings) {
        updateAppearanceCallCount += 1
        updateAppearanceArgValues.append(settings)
        if let updateAppearanceHandler = updateAppearanceHandler {
            updateAppearanceHandler(settings)
        }
        
    }

    private(set) var showCallCount = 0
    var showHandler: (() -> ())?
    func show() {
        showCallCount += 1
        if let showHandler = showHandler {
            showHandler()
        }
        
    }

    private(set) var hideCallCount = 0
    var hideHandler: (() -> ())?
    func hide() {
        hideCallCount += 1
        if let hideHandler = hideHandler {
            hideHandler()
        }
        
    }
}

fileprivate func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

fileprivate func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {
}

/// Will be replaced to `Synchronization.Mutex` in future.
fileprivate final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        self.value = initialValue
    }
#if compiler(>=6.0)
    borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#else
    func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#endif
}

fileprivate struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

fileprivate struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler? = nil
    var callCount: Int = 0
}

