///
/// @Generated by Mockolo
///



import AppKit
import Combine
import CoreWLAN
import Foundation
import IOKit
import KeyboardShortcuts
import SwiftUI
import os
@testable import SaneBar


final class PersistenceServiceProtocolMock: PersistenceServiceProtocol, @unchecked Sendable {
    init() { }


    private let saveSettingsState = MockoloMutex(MockoloHandlerState<SaneBarSettings, @Sendable (SaneBarSettings) throws -> ()>())
    var saveSettingsCallCount: Int {
        return saveSettingsState.withLock(\.callCount)
    }
    var saveSettingsArgValues: [SaneBarSettings] {
        return saveSettingsState.withLock(\.argValues).map(\.value)
    }
    var saveSettingsHandler: (@Sendable (SaneBarSettings) throws -> ())? {
        get { saveSettingsState.withLock(\.handler) }
        set { saveSettingsState.withLock { $0.handler = newValue } }
    }
    func saveSettings(_ settings: SaneBarSettings) throws {
        warnIfNotSendable(settings)
        let saveSettingsHandler = saveSettingsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((settings)))
            return state.handler
        }
        if let saveSettingsHandler = saveSettingsHandler {
            try saveSettingsHandler(settings)
        }
        
    }

    private let loadSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () throws -> SaneBarSettings>())
    var loadSettingsCallCount: Int {
        return loadSettingsState.withLock(\.callCount)
    }
    var loadSettingsHandler: (@Sendable () throws -> SaneBarSettings)? {
        get { loadSettingsState.withLock(\.handler) }
        set { loadSettingsState.withLock { $0.handler = newValue } }
    }
    func loadSettings() throws -> SaneBarSettings {
        let loadSettingsHandler = loadSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let loadSettingsHandler = loadSettingsHandler {
            return try loadSettingsHandler()
        }
        fatalError("loadSettingsHandler returns can't have a default value thus its handler must be set")
    }

    private let clearAllState = MockoloMutex(MockoloHandlerState<Never, @Sendable () throws -> ()>())
    var clearAllCallCount: Int {
        return clearAllState.withLock(\.callCount)
    }
    var clearAllHandler: (@Sendable () throws -> ())? {
        get { clearAllState.withLock(\.handler) }
        set { clearAllState.withLock { $0.handler = newValue } }
    }
    func clearAll() throws {
        let clearAllHandler = clearAllState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let clearAllHandler = clearAllHandler {
            try clearAllHandler()
        }
        
    }
}

final class SearchServiceProtocolMock: SearchServiceProtocol, @unchecked Sendable {
    init() { }


    private let getRunningAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getRunningAppsCallCount: Int {
        return getRunningAppsState.withLock(\.callCount)
    }
    var getRunningAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getRunningAppsState.withLock(\.handler) }
        set { getRunningAppsState.withLock { $0.handler = newValue } }
    }
    func getRunningApps() async -> [RunningApp] {
        let getRunningAppsHandler = getRunningAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getRunningAppsHandler = getRunningAppsHandler {
            return await getRunningAppsHandler()
        }
        return [RunningApp]()
    }

    private let getMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getMenuBarAppsCallCount: Int {
        return getMenuBarAppsState.withLock(\.callCount)
    }
    var getMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getMenuBarAppsState.withLock(\.handler) }
        set { getMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    func getMenuBarApps() async -> [RunningApp] {
        let getMenuBarAppsHandler = getMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getMenuBarAppsHandler = getMenuBarAppsHandler {
            return await getMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let getHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getHiddenMenuBarAppsCallCount: Int {
        return getHiddenMenuBarAppsState.withLock(\.callCount)
    }
    var getHiddenMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getHiddenMenuBarAppsState.withLock(\.handler) }
        set { getHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    func getHiddenMenuBarApps() async -> [RunningApp] {
        let getHiddenMenuBarAppsHandler = getHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getHiddenMenuBarAppsHandler = getHiddenMenuBarAppsHandler {
            return await getHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedMenuBarAppsCallCount: Int {
        return cachedMenuBarAppsState.withLock(\.callCount)
    }
    var cachedMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedMenuBarAppsState.withLock(\.handler) }
        set { cachedMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    @MainActor
    func cachedMenuBarApps() -> [RunningApp] {
        let cachedMenuBarAppsHandler = cachedMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedMenuBarAppsHandler = cachedMenuBarAppsHandler {
            return cachedMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedHiddenMenuBarAppsCallCount: Int {
        return cachedHiddenMenuBarAppsState.withLock(\.callCount)
    }
    var cachedHiddenMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedHiddenMenuBarAppsState.withLock(\.handler) }
        set { cachedHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    @MainActor
    func cachedHiddenMenuBarApps() -> [RunningApp] {
        let cachedHiddenMenuBarAppsHandler = cachedHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedHiddenMenuBarAppsHandler = cachedHiddenMenuBarAppsHandler {
            return cachedHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedVisibleMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedVisibleMenuBarAppsCallCount: Int {
        return cachedVisibleMenuBarAppsState.withLock(\.callCount)
    }
    var cachedVisibleMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedVisibleMenuBarAppsState.withLock(\.handler) }
        set { cachedVisibleMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    @MainActor
    func cachedVisibleMenuBarApps() -> [RunningApp] {
        let cachedVisibleMenuBarAppsHandler = cachedVisibleMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedVisibleMenuBarAppsHandler = cachedVisibleMenuBarAppsHandler {
            return cachedVisibleMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshMenuBarAppsCallCount: Int {
        return refreshMenuBarAppsState.withLock(\.callCount)
    }
    var refreshMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshMenuBarAppsState.withLock(\.handler) }
        set { refreshMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    func refreshMenuBarApps() async -> [RunningApp] {
        let refreshMenuBarAppsHandler = refreshMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshMenuBarAppsHandler = refreshMenuBarAppsHandler {
            return await refreshMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshHiddenMenuBarAppsCallCount: Int {
        return refreshHiddenMenuBarAppsState.withLock(\.callCount)
    }
    var refreshHiddenMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshHiddenMenuBarAppsState.withLock(\.handler) }
        set { refreshHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    func refreshHiddenMenuBarApps() async -> [RunningApp] {
        let refreshHiddenMenuBarAppsHandler = refreshHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshHiddenMenuBarAppsHandler = refreshHiddenMenuBarAppsHandler {
            return await refreshHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshVisibleMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshVisibleMenuBarAppsCallCount: Int {
        return refreshVisibleMenuBarAppsState.withLock(\.callCount)
    }
    var refreshVisibleMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshVisibleMenuBarAppsState.withLock(\.handler) }
        set { refreshVisibleMenuBarAppsState.withLock { $0.handler = newValue } }
    }
    func refreshVisibleMenuBarApps() async -> [RunningApp] {
        let refreshVisibleMenuBarAppsHandler = refreshVisibleMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshVisibleMenuBarAppsHandler = refreshVisibleMenuBarAppsHandler {
            return await refreshVisibleMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let activateState = MockoloMutex(MockoloHandlerState<RunningApp, @Sendable (RunningApp) async -> ()>())
    var activateCallCount: Int {
        return activateState.withLock(\.callCount)
    }
    var activateArgValues: [RunningApp] {
        return activateState.withLock(\.argValues).map(\.value)
    }
    var activateHandler: (@Sendable (RunningApp) async -> ())? {
        get { activateState.withLock(\.handler) }
        set { activateState.withLock { $0.handler = newValue } }
    }
    func activate(app: RunningApp) async {
        warnIfNotSendable(app)
        let activateHandler = activateState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((app)))
            return state.handler
        }
        if let activateHandler = activateHandler {
            await activateHandler(app)
        }
        
    }
}

final class NetworkTriggerServiceProtocolMock: NetworkTriggerServiceProtocol {
    init() { }
    init(currentSSID: String? = nil) {
        self.currentSSID = currentSSID
    }



    var currentSSID: String? = nil

    private(set) var configureCallCount = 0
    var configureArgValues = [MenuBarManager]()
    var configureHandler: ((MenuBarManager) -> ())?
    func configure(menuBarManager: MenuBarManager) {
        configureCallCount += 1
        configureArgValues.append(menuBarManager)
        if let configureHandler = configureHandler {
            configureHandler(menuBarManager)
        }
        
    }

    private(set) var startMonitoringCallCount = 0
    var startMonitoringHandler: (() -> ())?
    func startMonitoring() {
        startMonitoringCallCount += 1
        if let startMonitoringHandler = startMonitoringHandler {
            startMonitoringHandler()
        }
        
    }

    private(set) var stopMonitoringCallCount = 0
    var stopMonitoringHandler: (() -> ())?
    func stopMonitoring() {
        stopMonitoringCallCount += 1
        if let stopMonitoringHandler = stopMonitoringHandler {
            stopMonitoringHandler()
        }
        
    }
}

final class HoverServiceProtocolMock: HoverServiceProtocol {
    init() { }
    init(isEnabled: Bool = false, scrollEnabled: Bool = false, trackMouseLeave: Bool = false) {
        self.isEnabled = isEnabled
        self.scrollEnabled = scrollEnabled
        self.trackMouseLeave = trackMouseLeave
    }


    private(set) var isEnabledSetCallCount = 0
    var isEnabled: Bool = false { didSet { isEnabledSetCallCount += 1 } }

    private(set) var scrollEnabledSetCallCount = 0
    var scrollEnabled: Bool = false { didSet { scrollEnabledSetCallCount += 1 } }

    private(set) var trackMouseLeaveSetCallCount = 0
    var trackMouseLeave: Bool = false { didSet { trackMouseLeaveSetCallCount += 1 } }

    private(set) var startCallCount = 0
    var startHandler: (() -> ())?
    func start() {
        startCallCount += 1
        if let startHandler = startHandler {
            startHandler()
        }
        
    }

    private(set) var stopCallCount = 0
    var stopHandler: (() -> ())?
    func stop() {
        stopCallCount += 1
        if let stopHandler = stopHandler {
            stopHandler()
        }
        
    }
}

@MainActor
final class StatusBarControllerProtocolMock: StatusBarControllerProtocol, @unchecked Sendable {
    nonisolated init() { }
    init(mainItem: NSStatusItem, separatorItem: NSStatusItem) {
        self.mainItem = mainItem
        self.separatorItem = separatorItem
    }

    // Non-optional status items (matching protocol)
    var mainItem: NSStatusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    var separatorItem: NSStatusItem = NSStatusBar.system.statusItem(withLength: 20)

    private(set) var iconNameCallCount = 0
    var iconNameArgValues = [HidingState]()
    var iconNameHandler: ((HidingState) -> String)?
    func iconName(for state: HidingState) -> String {
        iconNameCallCount += 1
        iconNameArgValues.append(state)
        if let iconNameHandler = iconNameHandler {
            return iconNameHandler(state)
        }
        return ""
    }

    private(set) var createMenuCallCount = 0
    var createMenuArgValues = [MenuConfiguration]()
    var createMenuHandler: ((MenuConfiguration) -> NSMenu)?
    func createMenu(configuration: MenuConfiguration) -> NSMenu {
        createMenuCallCount += 1
        createMenuArgValues.append(configuration)
        if let createMenuHandler = createMenuHandler {
            return createMenuHandler(configuration)
        }
        fatalError("createMenuHandler returns can't have a default value thus its handler must be set")
    }
}

final class SettingsControllerProtocolMock: SettingsControllerProtocol {
    init() { }
    init(settings: SaneBarSettings) {
        self._settings = settings
    }


    private(set) var settingsSetCallCount = 0
    private var _settings: SaneBarSettings! { didSet { settingsSetCallCount += 1 } }
    var settings: SaneBarSettings {
        get { return _settings }
        set { _settings = newValue }
    }

    var settingsPublisher: AnyPublisher<SaneBarSettings, Never> { return self.settingsPublisherSubject.eraseToAnyPublisher() }
    private(set) var settingsPublisherSubject = PassthroughSubject<SaneBarSettings, Never>()

    private(set) var loadCallCount = 0
    var loadHandler: (() throws -> ())?
    func load() throws {
        loadCallCount += 1
        if let loadHandler = loadHandler {
            try loadHandler()
        }
        
    }

    private(set) var saveCallCount = 0
    var saveHandler: (() throws -> ())?
    func save() throws {
        saveCallCount += 1
        if let saveHandler = saveHandler {
            try saveHandler()
        }
        
    }
}

final class TriggerServiceProtocolMock: TriggerServiceProtocol {
    init() { }


    private(set) var configureCallCount = 0
    var configureArgValues = [MenuBarManager]()
    var configureHandler: ((MenuBarManager) -> ())?
    func configure(menuBarManager: MenuBarManager) {
        configureCallCount += 1
        configureArgValues.append(menuBarManager)
        if let configureHandler = configureHandler {
            configureHandler(menuBarManager)
        }
        
    }

    private(set) var stopMonitoringCallCount = 0
    var stopMonitoringHandler: (() -> ())?
    func stopMonitoring() {
        stopMonitoringCallCount += 1
        if let stopMonitoringHandler = stopMonitoringHandler {
            stopMonitoringHandler()
        }
        
    }
}

final class HidingServiceProtocolMock: HidingServiceProtocol {
    init() { }
    init(state: HidingState, isAnimating: Bool = false) {
        self._state = state
        self.isAnimating = isAnimating
    }



    private var _state: HidingState!
    var state: HidingState {
        get { return _state }
        set { _state = newValue }
    }


    var isAnimating: Bool = false

    private(set) var configureCallCount = 0
    var configureArgValues = [StatusItemProtocol]()
    var configureHandler: ((StatusItemProtocol) -> ())?
    func configure(delimiterItem: StatusItemProtocol) {
        configureCallCount += 1
        configureArgValues.append(delimiterItem)
        if let configureHandler = configureHandler {
            configureHandler(delimiterItem)
        }
        
    }

    private(set) var toggleCallCount = 0
    var toggleHandler: (() async -> ())?
    func toggle() async {
        toggleCallCount += 1
        if let toggleHandler = toggleHandler {
            await toggleHandler()
        }
        
    }

    private(set) var showCallCount = 0
    var showHandler: (() async -> ())?
    func show() async {
        showCallCount += 1
        if let showHandler = showHandler {
            await showHandler()
        }
        
    }

    private(set) var hideCallCount = 0
    var hideHandler: (() async -> ())?
    func hide() async {
        hideCallCount += 1
        if let hideHandler = hideHandler {
            await hideHandler()
        }
        
    }
}

final class KeyboardShortcutsServiceProtocolMock: KeyboardShortcutsServiceProtocol {
    init() { }


    private(set) var registerAllHandlersCallCount = 0
    var registerAllHandlersHandler: (() -> ())?
    func registerAllHandlers() {
        registerAllHandlersCallCount += 1
        if let registerAllHandlersHandler = registerAllHandlersHandler {
            registerAllHandlersHandler()
        }
        
    }

    private(set) var unregisterAllHandlersCallCount = 0
    var unregisterAllHandlersHandler: (() -> ())?
    func unregisterAllHandlers() {
        unregisterAllHandlersCallCount += 1
        if let unregisterAllHandlersHandler = unregisterAllHandlersHandler {
            unregisterAllHandlersHandler()
        }
        
    }
}

final class MenuBarAppearanceServiceProtocolMock: MenuBarAppearanceServiceProtocol {
    init() { }


    private(set) var updateAppearanceCallCount = 0
    var updateAppearanceArgValues = [MenuBarAppearanceSettings]()
    var updateAppearanceHandler: ((MenuBarAppearanceSettings) -> ())?
    func updateAppearance(_ settings: MenuBarAppearanceSettings) {
        updateAppearanceCallCount += 1
        updateAppearanceArgValues.append(settings)
        if let updateAppearanceHandler = updateAppearanceHandler {
            updateAppearanceHandler(settings)
        }
        
    }

    private(set) var showCallCount = 0
    var showHandler: (() -> ())?
    func show() {
        showCallCount += 1
        if let showHandler = showHandler {
            showHandler()
        }
        
    }

    private(set) var hideCallCount = 0
    var hideHandler: (() -> ())?
    func hide() {
        hideCallCount += 1
        if let hideHandler = hideHandler {
            hideHandler()
        }
        
    }
}

fileprivate func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

fileprivate func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {
}

/// Will be replaced to `Synchronization.Mutex` in future.
fileprivate final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        self.value = initialValue
    }
#if compiler(>=6.0)
    borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#else
    func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#endif
}

fileprivate struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

fileprivate struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler? = nil
    var callCount: Int = 0
}

