///
/// @Generated by Mockolo
///

import Foundation
@testable import SaneBar

class PersistenceServiceProtocolMock: PersistenceServiceProtocol, @unchecked Sendable {
    var settings: SaneBarSettings = SaneBarSettings()

    func saveSettings(_ settings: SaneBarSettings) throws {
        self.settings = settings
    }

    func loadSettings() throws -> SaneBarSettings {
        return settings
    }

    func clearAll() throws {
        settings = SaneBarSettings()
    }
}
