disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name
  - line_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - shorthand_operator

file_length:
  warning: 500
  error: 800

opt_in_rules:
  - empty_count
  - empty_string

included:
  - Core
  - UI
  - SaneBarApp.swift

excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - .swiftpm
  - Tests
  - Scripts

# Configure specific rules if re-enabled later
