name: SaneBar
options:
  bundleIdPrefix: com.sanevideo
  deploymentTarget:
    macOS: 14.0
  xcodeVersion: 16.0

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin
    from: 5.0.0
settings:
  DEAD_CODE_STRIPPING: YES
  SWIFT_EMIT_LOC_STRINGS: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  ENABLE_HARDENED_RUNTIME: YES
  GENERATE_INFOPLIST_FILE: YES
  # Recommended warnings
  CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
  CLANG_WARN_BOOL_CONVERSION: YES
  CLANG_WARN_COMMA: YES
  CLANG_WARN_CONSTANT_CONVERSION: YES
  CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
  CLANG_WARN_EMPTY_BODY: YES
  CLANG_WARN_ENUM_CONVERSION: YES
  CLANG_WARN_INFINITE_RECURSION: YES
  CLANG_WARN_INT_CONVERSION: YES
  CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
  CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
  CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
  CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
  CLANG_WARN_STRICT_PROTOTYPES: YES
  CLANG_WARN_SUSPICIOUS_MOVE: YES
  CLANG_WARN_UNREACHABLE_CODE: YES
  CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
  ENABLE_STRICT_OBJC_MSGSEND: YES
  GCC_NO_COMMON_BLOCKS: YES
  GCC_WARN_64_TO_32_BIT_CONVERSION: YES
  GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
  GCC_WARN_UNDECLARED_SELECTOR: YES
  GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
  GCC_WARN_UNUSED_FUNCTION: YES
  GCC_WARN_UNUSED_VARIABLE: YES

schemes:
  SaneBar:
    build:
      targets:
        SaneBar: all
        SaneBarTests: [test]
    test:
      targets:
        - SaneBarTests
    profile:
      config: Release
    run:
      config: Debug
    archive:
      config: Release

targets:
  SaneBar:
    type: application
    platform: macOS
    bundleId: com.sanevideo.SaneBar
    deploymentTarget:
      macOS: 14.0
    sources:
      - SaneBarApp.swift
      - Core
      - UI
      - Resources
    dependencies:
      - package: KeyboardShortcuts
      - package: LaunchAtLogin
    info:
      path: SaneBar/Info.plist
      properties:
        NSAppleScriptEnabled: true
        OSAScriptingDefinition: SaneBar.sdef
    settings:
      base:
        PRODUCT_NAME: SaneBar
        PRODUCT_BUNDLE_IDENTIFIER: com.sanevideo.SaneBar
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 6.0
        MACOSX_DEPLOYMENT_TARGET: 14.0
        ARCHS: arm64
        VALID_ARCHS: arm64
        DEVELOPMENT_TEAM: M78L6FXD48
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_ENTITLEMENTS: SaneBar/SaneBar.entitlements
        Release:
          CODE_SIGN_IDENTITY: "Developer ID Application: Stephan Joseph (M78L6FXD48)"
          CODE_SIGN_ENTITLEMENTS: SaneBar/SaneBar.entitlements
    postCompileScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint . || true
          else
            echo "warning: SwiftLint not installed"
          fi
        name: Run SwiftLint

  SaneBarTests:
    type: bundle.unit-test
    platform: macOS
    bundleId: com.sanevideo.SaneBarTests
    deploymentTarget:
      macOS: 14.0
    sources:
      - Tests
    dependencies:
      - target: SaneBar
    settings:
      base:
        DEVELOPMENT_TEAM: M78L6FXD48
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"