name: Bug Report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please provide details below.

  - type: input
    id: version
    attributes:
      label: SaneBar Version
      placeholder: "1.0.1"
    validations:
      required: true

  - type: input
    id: macos
    attributes:
      label: macOS Version
      placeholder: "Sequoia 15.2 / Tahoe 26.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      placeholder: Expected behavior

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open SaneBar
        2. Click...
        3. Bug occurs
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      description: Run `log show --predicate 'process == "SaneBar"' --last 5m` in Terminal
      render: shell
